# SALES ANALYSIS

# Calculate total sales generated by the business
SELECT ROUND(SUM(Sales),2) AS total_sales
FROM superstore;

# Calculate total profit generated by the business
SELECT ROUND(SUM(Profit),2) AS total_profit
FROM superstore;

# Analyze sales performance by product category
SELECT
    Category,
    ROUND(SUM(Sales),2) AS total_sales
FROM superstore
GROUP BY Category
ORDER BY total_sales DESC;

# Analyze profit contribution by category
SELECT
    Category,
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY Category
ORDER BY total_profit DESC;

# Analyze sales performance by region
SELECT
    Region,
    ROUND(SUM(Sales),2) AS total_sales
FROM superstore
GROUP BY Region
ORDER BY total_sales DESC;